name: Pull Data

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *" # 00:00 UTC = 07:00 WIB (UTC+7) = 08:00 WITA (UTC+8)
    # - cron: "0 13 * * *" # 13:00 UTC = 20:00 WIB (UTC+7) = 21:00 WITA (UTC+8)

env:
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
  TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
  TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run src/index.ts
